spring.application.name=ecom
spring.datasource.url=jdbc:h2:file:D:\\Study Material\\IBF\\java\\Projects\\ProjectDb\\ECOMUSERTEST;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.redis.host=localhost
spring.redis.port=6379